plugins:
    - jekyll-relative-links
    - jekyll-include-cache
    - jekyll-remote-theme
relative_links:
    enabled: true
    collections: true
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin: "air"
title: Cryptimeleon Documentation
subtitle: "Version 1.0.0"
repository: cryptimeleon/cryptimeleon.github.io
locale: en
description: Documentation page for the Cryptimeleon cryptography libraries.
defaults:
    # _pages
    - scope:
        path: ""
        type: pages
      values:
        layout: single
        classes: wide
        sidebar:
          nav: "docs"
kramdown:
    auto_ids: true
    hard_wrap: false

# exclude from jekyll site
exclude:
    - vendor
    - DEVELOPER.md
    - Gemfile
    - Gemfile.lock
    - README.md
    - Dockerfile
    - LICENSE