plugins:
    - jekyll-relative-links
    - jekyll-include-cache
    - jekyll-remote-theme
relative_links:
    enabled: true
    collections: true
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin: "air"
title: upb.crypto Documentation
subtitle: "Version 2.0"
repository: upbcuk/upb.crypto.docs
locale: en
description: Documentation page for the upb.crypto cryptography libraries.
defaults:
    # _pages
    - scope:
        path: ""
        type: pages
      values:
        layout: single
        classes: wide
        sidebar:
          nav: "docs"
kramdown:
    auto_ids: true

# exclude from jekyll site
exclude:
    - DEVELOPER.md
    - Gemfile
    - Gemfile.lock
    - README.md
    - Dockerfile
    - LICENSE