plugins:
    - jekyll-relative-links
    - jekyll-include-cache
relative_links:
    enabled: true
    collections: true
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"
title: Cryptimeleon
subtitle: Prototyping of Cryptographic Construction
logo: /assets/logo.png
repository: cryptimeleon/cryptimeleon.github.io
locale: en
atom_feed:
  hide: true
description: Documentation page for the Cryptimeleon cryptography libraries.
defaults:
    # _pages
    - scope:
        path: ""
        type: pages
      values:
        layout: single
        classes: wide
        sidebar:
          nav: "docs"
kramdown:
    auto_ids: true
    hard_wrap: false

cracoversion: 2.1.0
mathversion: 2.1.0

# exclude from jekyll site
exclude:
    - vendor
    - DEVELOPER.md
    - Gemfile
    - Gemfile.lock
    - README.md
    - Dockerfile
    - LICENSE
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/cryptimeleon"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cryptimeleon"
