name: Build and deploy Jekyll site to Github Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with: 
          python-version: "3.8"
          architecture: "x64"
        
      - name: Install Jupyter and nbtojekyll
        run: |
          python -m pip install notebook
          git clone https://github.com/rheitjoh/nbtojekyll.git
          cd nbtojekyll
          python -m pip install --upgrade --force-reinstall --no-deps --no-cache-dir .

      - name: Convert Jupyter notebooks
        run: |
          jupyter nbtojekyll getting-started/pairing-tutorial.ipynb --output getting-started/pairing-tutorial.md --binder-link https://mybinder.org/v2/gh/cryptimeleon/cryptimeleon.github.io/master\?filepath\=getting-started%2Fpairing-tutorial.ipynb --image-dir /assets/images/pairing-tutorial --md-title "Pairing Tutorial" --binder-link-cell 1 --enable-toc --enable-mathjax
          jupyter nbtojekyll getting-started/protocols-tutorial.ipynb --output getting-started/protocols-tutorial.md --binder-link https://mybinder.org/v2/gh/cryptimeleon/cryptimeleon.github.io/master\?filepath\=getting-started%2Fprotocols-tutorial.ipynb --image-dir assets/images/protocols-tutorial --md-title "Protocols Tutorial" --binder-link-cell 0 --enable-toc --enable-mathjax
          jupyter nbtojekyll getting-started/5-minute-tutorial.ipynb --output getting-started/5-minute-tutorial.md --binder-link https://mybinder.org/v2/gh/cryptimeleon/cryptimeleon.github.io/master\?filepath\=getting-started%2F5-minute-tutorial.ipynb --image-dir assets/images/5-minute-tutorial --md-title "5 Minute Tutorial" --binder-link-cell 0 --enable-toc --enable-mathjax

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.JEKYLL_PAT }}
          target_branch: "gh-pages"
